# data initialization files
storage.trainers.file=classpath:data/trainers.csv
storage.trainees.file=classpath:data/trainees.csv
storage.trainings.file=classpath:data/trainings.csv

# csv parser configuration
csv.header=true
csv.delimiter=;
csv.ignoreQuotations=false
