# data initialization files
storage.initialize=true
storage.data-locations=classpath:data/trainer.csv, classpath:data/trainee.csv, classpath:data/training.csv

# csv parser configuration
csv.header=true
csv.delimiter=;
csv.ignoreQuotations=false
